### ISSUE TITLE
Build error: Cannot find module '!raw-loader!../public/styles.css'

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#104]
I get this error during the `static-site/` build when running `npm run build`. The build does seem to finish successfully despite it, but I'm not sure if `public/styles.css` is missing or not because of the error.

```
success Building production JavaScript and CSS bundles - 10.811s
success Rewriting compilation hashes - 0.004s
warn code block or inline code language not specified in markdown. applying generic code block
success run queries - 14.970s - 32/32 2.14/s
success Generating image thumbnails - 50.678s - 379/379 7.48/s
[                            ]   0.001 s 0/32 0% Building static HTML for pages
{ Error: Cannot find module '!raw-loader!../public/styles.css'
    at webpackMissingModule (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:6760:79)
    at Module../src/html.jsx (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:6760:186)
    at __webpack_require__ (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:30:30)
    at Module../.cache/static-entry.js (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:646:222)
    at __webpack_require__ (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:30:30)
    at ../favicon.png.module.exports (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:94:18)
    at /home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:97:10
    at webpackUniversalModuleDefinition (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:3:20)
    at Object.<anonymous> (/home/tom/nextstrain/nextstrain.org/static-site/public/render-page.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18) code: 'MODULE_NOT_FOUND' }
success Building static HTML for pages - 2.447s - 32/32 13.08/s
```

**Comment by jameshadfield** [comment]
See https://github.com/nextstrain/nextstrain.org/pull/75#issuecomment-574019845 for context / more info
