### ISSUE TITLE
Invalid blog URLs are unhandled 500 errors

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#1093]
Going to an invalid URL under `/blog` such as https://nextstrain.org/blog/invalid shows Next.js's **500: Internal Server Error** page.

<img width="403" alt="image" src="https://github.com/user-attachments/assets/9dfc42a6-9367-4fd7-ab32-627c49aa4c5f" />

## Possible solutions

Catch the error and:

1. Redirect to `/blog`
2. Show an error page similar to the one that appears when there is a Markdown parsing error:

    <img width="932" alt="image" src="https://github.com/user-attachments/assets/b85962f4-338f-44ea-95cc-e0abf38af365" />

**Comment by genehack** [comment]
@victorlin this is probably my fault — I can get it unless you want it?

**Comment by victorlin** [comment]
> this is probably my fault

No worries, I don't remember if we had anything in place before your blog changes. It's possible that it was already broken.

> I can get it unless you want it?

All yours!

**Comment by victorlin** [comment]
Are you planning to (1) redirect or (2) show a custom error page? I've a slight preference for (2)

**Comment by genehack** [comment]
> Are you planning to (1) redirect or (2) show a custom error page? I've a slight preference for (2)

I was going to make it properly 404, ala https://next.nextstrain.org/contact/foo

**Comment by genehack** [comment]
Can't reproduce this locally (even using `USE_PREBUILT_STATIC_SITE=1`), but still see it happening on the live site.

**Comment by jameshadfield** [comment]
Here's the log (from nextstrain-canary) when attempting /blog/invalid:

```console
$ heroku logs --app nextstrain-canary --tail
2025-02-04T01:46:12.841773+00:00 heroku[router]: at=info method=GET path="/blog/invalid" host=next.nextstrain.org request_id=aebb6c5b-9e20-42dd-ba40-b0f3bf4a4988 fwd="125.236.205.234" dyno=web.1 connect=0ms service=36ms status=500 bytes=1999 protocol=https
2025-02-04T01:46:12.809271+00:00 app[web.1]: [verbose]  next.js handling request for "/blog/invalid"
2025-02-04T01:46:12.816296+00:00 app[web.1]: Error: ENOENT: no such file or directory, scandir '/build/app/static-site/content/blog'
2025-02-04T01:46:12.816298+00:00 app[web.1]: at Object.readdirSync (node:fs:1506:26)
2025-02-04T01:46:12.816298+00:00 app[web.1]: at b (/app/static-site/.next/server/app/blog/[id]/page.js:6:1709)
2025-02-04T01:46:12.816298+00:00 app[web.1]: at h (/app/static-site/.next/server/app/blog/[id]/page.js:1:3116)
2025-02-04T01:46:12.816299+00:00 app[web.1]: at em (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
2025-02-04T01:46:12.816299+00:00 app[web.1]: at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
2025-02-04T01:46:12.816299+00:00 app[web.1]: at Array.toJSON (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
2025-02-04T01:46:12.816300+00:00 app[web.1]: at stringify (<anonymous>)
2025-02-04T01:46:12.816300+00:00 app[web.1]: at eR (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
2025-02-04T01:46:12.816300+00:00 app[web.1]: at eP (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
2025-02-04T01:46:12.816301+00:00 app[web.1]: at AsyncLocalStorage.run (node:async_hooks:346:14) {
2025-02-04T01:46:12.816302+00:00 app[web.1]: errno: -2,
2025-02-04T01:46:12.816302+00:00 app[web.1]: code: 'ENOENT',
2025-02-04T01:46:12.816303+00:00 app[web.1]: syscall: 'scandir',
2025-02-04T01:46:12.816303+00:00 app[web.1]: path: '/build/app/static-site/content/blog'
2025-02-04T01:46:12.816303+00:00 app[web.1]: }
2025-02-04T01:46:12.816413+00:00 app[web.1]: Error: ENOENT: no such file or directory, scandir '/build/app/static-site/content/blog'
2025-02-04T01:46:12.816413+00:00 app[web.1]: at Object.readdirSync (node:fs:1506:26)
2025-02-04T01:46:12.816413+00:00 app[web.1]: at b (/app/static-site/.next/server/app/blog/[id]/page.js:6:1709)
2025-02-04T01:46:12.816413+00:00 app[web.1]: at Module.d (/app/static-site/.next/server/app/blog/[id]/page.js:1:2814)
2025-02-04T01:46:12.816414+00:00 app[web.1]: at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:225508
2025-02-04T01:46:12.816424+00:00 app[web.1]: at /app/node_modules/next/dist/server/lib/trace/tracer.js:133:36
2025-02-04T01:46:12.816424+00:00 app[web.1]: at NoopContextManager.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
2025-02-04T01:46:12.816424+00:00 app[web.1]: at ContextAPI.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
2025-02-04T01:46:12.816424+00:00 app[web.1]: at NoopTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
2025-02-04T01:46:12.816425+00:00 app[web.1]: at ProxyTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
2025-02-04T01:46:12.816425+00:00 app[web.1]: at /app/node_modules/next/dist/server/lib/trace/tracer.js:122:103 {
2025-02-04T01:46:12.816425+00:00 app[web.1]: errno: -2,
2025-02-04T01:46:12.816425+00:00 app[web.1]: code: 'ENOENT',
2025-02-04T01:46:12.816425+00:00 app[web.1]: syscall: 'scandir',
2025-02-04T01:46:12.816426+00:00 app[web.1]: path: '/build/app/static-site/content/blog'
2025-02-04T01:46:12.816426+00:00 app[web.1]: }
2025-02-04T01:46:12.820888+00:00 app[web.1]: Error: ENOENT: no such file or directory, scandir '/build/app/static-site/content/blog'
2025-02-04T01:46:12.820889+00:00 app[web.1]: at Object.readdirSync (node:fs:1506:26)
2025-02-04T01:46:12.820890+00:00 app[web.1]: at b (/app/static-site/.next/server/app/blog/[id]/page.js:6:1709)
2025-02-04T01:46:12.820890+00:00 app[web.1]: at h (/app/static-site/.next/server/app/blog/[id]/page.js:1:3116)
2025-02-04T01:46:12.820890+00:00 app[web.1]: at em (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
2025-02-04T01:46:12.820891+00:00 app[web.1]: at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
2025-02-04T01:46:12.820891+00:00 app[web.1]: at Array.toJSON (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
2025-02-04T01:46:12.820891+00:00 app[web.1]: at stringify (<anonymous>)
2025-02-04T01:46:12.820892+00:00 app[web.1]: at eR (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
2025-02-04T01:46:12.820892+00:00 app[web.1]: at eP (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
2025-02-04T01:46:12.820892+00:00 app[web.1]: at Timeout._onTimeout (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132091) {
2025-02-04T01:46:12.820893+00:00 app[web.1]: errno: -2,
2025-02-04T01:46:12.820893+00:00 app[web.1]: code: 'ENOENT',
2025-02-04T01:46:12.820893+00:00 app[web.1]: syscall: 'scandir',
2025-02-04T01:46:12.820893+00:00 app[web.1]: path: '/build/app/static-site/content/blog'
2025-02-04T01:46:12.820893+00:00 app[web.1]: }
2025-02-04T01:46:12.821255+00:00 app[web.1]: Error: ENOENT: no such file or directory, scandir '/build/app/static-site/content/blog'
2025-02-04T01:46:12.821255+00:00 app[web.1]: at Object.readdirSync (node:fs:1506:26)
2025-02-04T01:46:12.821255+00:00 app[web.1]: at b (/app/static-site/.next/server/app/blog/[id]/page.js:6:1709)
2025-02-04T01:46:12.821256+00:00 app[web.1]: at Module.d (/app/static-site/.next/server/app/blog/[id]/page.js:1:2814)
2025-02-04T01:46:12.821256+00:00 app[web.1]: at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:225508
2025-02-04T01:46:12.821256+00:00 app[web.1]: at /app/node_modules/next/dist/server/lib/trace/tracer.js:133:36
2025-02-04T01:46:12.821256+00:00 app[web.1]: at NoopContextManager.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
2025-02-04T01:46:12.821256+00:00 app[web.1]: at ContextAPI.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
2025-02-04T01:46:12.821257+00:00 app[web.1]: at NoopTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
2025-02-04T01:46:12.821257+00:00 app[web.1]: at ProxyTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
2025-02-04T01:46:12.821257+00:00 app[web.1]: at /app/node_modules/next/dist/server/lib/trace/tracer.js:122:103 {
2025-02-04T01:46:12.821257+00:00 app[web.1]: errno: -2,
2025-02-04T01:46:12.821257+00:00 app[web.1]: code: 'ENOENT',
2025-02-04T01:46:12.821258+00:00 app[web.1]: syscall: 'scandir',
2025-02-04T01:46:12.821258+00:00 app[web.1]: path: '/build/app/static-site/content/blog'
2025-02-04T01:46:12.821258+00:00 app[web.1]: }
2025-02-04T01:46:12.822929+00:00 app[web.1]: [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
2025-02-04T01:46:12.822930+00:00 app[web.1]: digest: '1501199230'
2025-02-04T01:46:12.822930+00:00 app[web.1]: }
2025-02-04T01:46:12.834834+00:00 app[web.1]: ⨯ Error: ENOENT: no such file or directory, scandir '/build/app/static-site/content/blog'
2025-02-04T01:46:12.834835+00:00 app[web.1]: at Object.readdirSync (node:fs:1506:26)
2025-02-04T01:46:12.834835+00:00 app[web.1]: at b (/app/static-site/.next/server/app/blog/[id]/page.js:6:1709)
2025-02-04T01:46:12.834835+00:00 app[web.1]: at h (/app/static-site/.next/server/app/blog/[id]/page.js:1:3116)
2025-02-04T01:46:12.834835+00:00 app[web.1]: at em (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131205)
2025-02-04T01:46:12.834836+00:00 app[web.1]: at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142906
2025-02-04T01:46:12.834836+00:00 app[web.1]: at Array.toJSON (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146484)
2025-02-04T01:46:12.834837+00:00 app[web.1]: at stringify (<anonymous>)
2025-02-04T01:46:12.834837+00:00 app[web.1]: at eR (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134868)
2025-02-04T01:46:12.834837+00:00 app[web.1]: at eP (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135311)
2025-02-04T01:46:12.834838+00:00 app[web.1]: at AsyncLocalStorage.run (node:async_hooks:346:14) {
2025-02-04T01:46:12.834838+00:00 app[web.1]: errno: -2,
2025-02-04T01:46:12.834838+00:00 app[web.1]: code: 'ENOENT',
2025-02-04T01:46:12.834839+00:00 app[web.1]: syscall: 'scandir',
2025-02-04T01:46:12.834839+00:00 app[web.1]: path: '/build/app/static-site/content/blog'
2025-02-04T01:46:12.834839+00:00 app[web.1]: }
```





> Can't reproduce this locally ...

I guessed this was because you're not running in production mode, however even in production mode I get the 404 splash page not a 500 error page. In case it helps, I run in production mode via `PORT=5001 REDIS_REQUIRED=false SESSION_SECRET=1 NODE_ENV=production RESOURCE_INDEX=false USE_PREBUILT_STATIC_SITE=1 node server.js --verbose` and the following patch, but I know @tsibley has a more legitimate approach

```diff
diff --git a/src/authn/session.js b/src/authn/session.js
index 46d9aa4a..9bdffc55 100644
--- a/src/authn/session.js
+++ b/src/authn/session.js
@@ -4,9 +4,9 @@ import { keyringFromParamString, encrypt, decrypt, randomKey } from '../cryptogr
 
 const SESSION_ENCRYPTION_KEYS = process.env.SESSION_ENCRYPTION_KEYS;
 
-if (PRODUCTION && !SESSION_ENCRYPTION_KEYS) {
-  throw new Error("SESSION_ENCRYPTION_KEYS required in production mode");
-}
+// if (PRODUCTION && !SESSION_ENCRYPTION_KEYS) {
+//   throw new Error("SESSION_ENCRYPTION_KEYS required in production mode");
+// }
 
 const KEYRING = keyringFromParamString(SESSION_ENCRYPTION_KEYS || `RANDOM=${randomKey()}`);
 
diff --git a/src/routing/setup.js b/src/routing/setup.js
index 95f024f7..a1fb4bf6 100644
--- a/src/routing/setup.js
+++ b/src/routing/setup.js
@@ -26,7 +26,7 @@ export function setupApp() {
   // metadata from the proxy.
   if (PRODUCTION) app.enable("trust proxy");
 
-  if (PRODUCTION) app.use(sslRedirect()); // redirect HTTP to HTTPS
+  // if (PRODUCTION) app.use(sslRedirect()); // redirect HTTP to HTTPS
   app.use(compression()); // send files (e.g. res.json()) using compression (if possible)
   app.use(nakedRedirect({reverse: true})); // redirect www.nextstrain.org to nextstrain.org
   app.use(middleware.rejectParentTraversals);
```

**Comment by genehack** [comment]
> Here's the log (from nextstrain-canary) when attempting /blog/invalid:

thanks — i figured out how to see the logs on heroku after a bit of hide-and-seek and figured out the problem! [PR](https://github.com/nextstrain/nextstrain.org/pull/1115) is ready for review…

**Comment by tsibley** [comment]
[Local repro](https://github.com/nextstrain/nextstrain.org/pull/1115#discussion_r1942372725), FWIW.
