### ISSUE TITLE
catch (minor) fetch error

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#32]
The github API call for staging narratives fails (as there's no "staging" branch in the repo) at https://github.com/nextstrain/nextstrain.org/blob/master/auspice/server/sources.js#L102 and isn't caught. It doesn't bring down the server but could be nicer. (I'm happy to take this once i'm back home.)

```
(node:58366) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/nextstrain/narratives/contents?ref=staging failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/Users/naboo/github/nextstrain/nextstrain.org/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:58366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58366) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tsibley** [comment]
There is actually a staging branch in the narratives repo: https://github.com/nextstrain/narratives/tree/staging. I created it when I pushed my nextstrain.org work up.

The reason for the error you pasted is found at the end of the first line:

```
getaddrinfo ENOTFOUND api.github.com api.github.com:443
```

This is a DNS resolution failure, which is likely transient and may be localized to your network.
